from .test_plage_model import PlageModelTest
from .test_question_model import QuestionModelTest
from .test_qcm_model import QCMModelTest
from .test_reponse_model import ReponseModelTest
from .test_tag_model import TagModelTest
from .test_utilisateur_model import UtilisateurModelTest
from .test_reponseqcm_model import ReponseQCMModelTest
from .test_reponsequestion_model import ReponseQuestionModelTest
