# Generated by Django 5.1.1 on 2024-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponseqcm',
            name='date_fin_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
