# Generated by Django 5.1.1 on 2024-09-17 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app.question')),
                ('reponse', models.ManyToManyField(related_name='reponses', to='app.reponse')),
            ],
            options={
                'verbose_name': 'Réponse Question',
                'verbose_name_plural': 'Réponses Questions',
            },
        ),
        migrations.AddField(
            model_name='reponseqcm',
            name='reponses',
            field=models.ManyToManyField(to='app.reponsequestion'),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Enseignant', 'Enseignant')], default='Etudiant', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='utilisateur_groups', to='auth.group', verbose_name='groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilisateur_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.AddField(
            model_name='reponsequestion',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='app.utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='reponseqcm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reponseqcm',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_qcm', to='app.utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='reponseqcm',
            unique_together={('utilisateur', 'qcm', 'date_reponse')},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterUniqueTogether(
            name='reponsequestion',
            unique_together={('utilisateur', 'question', 'date')},
        ),
        migrations.RemoveField(
            model_name='reponseqcm',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='reponseqcm',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reponseqcm',
            name='reponse',
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
    ]
