# Generated by Django 5.1.1 on 2024-09-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number_of_correct_answers',
        ),
    ]
