# Generated by Django 5.1.1 on 2024-09-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_number_of_correct_answers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('texte',)},
        ),
    ]
