# Generated by Django 5.1.1 on 2024-09-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
