# Generated by Django 5.1.1 on 2024-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_plage_groupe_alter_plage_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
