# Generated by Django 5.1.1 on 2024-09-12 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
