# Generated by Django 5.1.1 on 2024-11-20 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_auto_20240930_0911"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcm",
            name="date_creation",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
