# Generated by Django 5.1.1 on 2024-09-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_question_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
