# Generated by Django 5.1.1 on 2024-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='est_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcm',
            name='nb_reponses',
            field=models.IntegerField(default=1),
        ),
    ]
