# Generated by Django 5.1.1 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_qcm_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
    ]
