# Generated by Django 5.1.1 on 2024-09-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_melange_rep_question_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='melange_rep',
            field=models.BooleanField(default=True),
        ),
    ]
