# Generated by Django 5.1.1 on 2024-11-22 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_question_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qcm",
            old_name="nb_reponses",
            new_name="nb_tentatives",
        ),
    ]
