from .question_list_view import QuestionListView
from .question_create_or_edit_view import create_or_edit_question
from .login_view import CustomLoginView
from .remove_tags_view import remove_tag
from .delete_question_view import delete_question
from .home_view import home
from .qcm_creation_view import create_qcm
from .qcm_list_view import QcmListView
from .export_question_view import export_question
from .support_doc_view import support_doc
from .etudiant_dashboard_view import etudiant_dashboard
