name: pre-commit

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      id: pre-commit
      run: |
        set +e
        pre-commit run --all-files
        EXIT_CODE=$?
        echo "Pre-commit exit code: $EXIT_CODE"
        echo "exit_code=$EXIT_CODE" >> $GITHUB_ENV
        set -e

    # Créer une Pull Request si des changements sont détectés sur une pull request existante
    - name: Create Pull Request if changes on pull request
      if: ${{ env.exit_code != '0' && github.event_name == 'pull_request' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-pr-${{ github.event.pull_request.number }}
        title: "Fix pre-commit linting issues in PR #${{ github.event.pull_request.number }}"
        body: "Automatic pre-commit fixes for PR #${{ github.event.pull_request.number }}"
        labels: pre-commit, auto-fix
        base: ${{ github.event.pull_request.base.ref }}
        # update_existing: true

    # Créer une Pull Request si des changements sont détectés sur un push
    - name: Create Pull Request if changes on push
      if: ${{ env.exit_code != '0' && github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-${{ github.ref_name }}
        title: "Fix pre-commit linting issues in ${github.ref_name}"
        body: "Automatic pre-commit fixes"
        labels: pre-commit, auto-fix
        base: ${{ github.ref_name }}
        # update_existing: true

    # Échouer le workflow si des problèmes sont détectés
    - name: Fail if pre-commit issues found
      if: ${{ env.exit_code != '0' }}
      run: |
        echo "Pre-commit issues found. Please fix them."
        exit 1

    - name: Finish
      if: ${{ env.exit_code == '0' }}
      run: |
        echo "No pre-commit issues found."
