name: pre-commit

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Pour les pull requests, vérifier le code du PR
        # Pour les pushs, vérifier le code de la branche
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        fetch-depth: 0  # Récupère toutes les branches et l'historique

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      id: pre-commit
      run: |
        pre-commit run --all-files || EXIT_CODE=$?
        echo "Pre-commit exit code: $EXIT_CODE"
        echo "exit_code=$EXIT_CODE" >> $GITHUB_ENV

    # Pour les pushs sur 'main' ou 'dev', corriger automatiquement les problèmes
    - name: Commit changes if any on pull request and push
      if: ${{ env.exit_code == '1'}}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "pre-commit fixes"

    - name: Create Pull Request if changes on pull request
      if: ${{ env.exit_code == '1' && github.event_name == 'pull_request' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-${{ github.ref_name }}
        title: "Fix pre-commit linting issues"
        body: "Automatic pre-commit fixes"
        labels: pre-commit, auto-fix
        base: ${{ github.base_ref }}

    - name: Create Pull Request if changes on push
      if: ${{ env.exit_code == '1' && github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-${{ github.ref_name }}
        title: "Fix pre-commit linting issues"
        body: "Automatic pre-commit fixes"
        labels: pre-commit, auto-fix
        base: ${{ github.ref }}

    # Pour les pull requests, échouer si des problèmes sont détectés
    - name: Fail if pre-commit issues found
      if: ${{ env.exit_code != '0' && github.event_name == 'pull_request' }}
      run: |
        echo "Pre-commit issues found. Please fix them."
        exit 1

    - name: Finish
      if: ${{ env.exit_code == '0' }}
      run: |
        echo "No pre-commit issues found."
