name: pre-commit

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      id: pre-commit
      run: |
        exit_code=0
        pre-commit run --all-files || exit_code=$?
        echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        exit $exit_code

    - name: Commit changes if any
      if: ${{ github.event_name == 'push' && steps.pre-commit.outputs.exit_code == '1' }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "pre-commit fixes"

    - name: Create Pull Request if changes
      if: ${{ github.event_name == 'push' && steps.pre-commit.outputs.exit_code == '1' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-${{ github.ref_name }}
        title: "Fix pre-commit linting issues"
        body: "Automatic pre-commit fixes"
        labels: pre-commit, auto-fix
        base: ${{ github.ref_name }}

    # Pour les pull requests, échouer si des problèmes sont détectés
    - name: Fail if pre-commit issues found
      if: ${{ steps.pre-commit.outputs.exit_code != '0' && github.event_name == 'pull_request' }}
      run: |
        echo "Pre-commit issues found. Please fix them."
        exit 1
