name: pre-commit

on:
  pull_request:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      id: pre-commit
      run: |
        pre-commit run --all-files || EXIT_CODE=$?
        echo "Pre-commit exit code: $EXIT_CODE"
        echo "exit_code=$EXIT_CODE" >> $GITHUB_ENV

    - name: Commit changes if any
      if: ${{ env.exit_code == '1' }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "pre-commit fixes"

    - name: Create Pull Request if changes
      if: ${{ env.exit_code == '1' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: pre-commit fixes
        branch: fix/pre-commit-fixes-${{ github.ref_name }}
        title: "Fix pre-commit linting issues"
        body: "Automatic pre-commit fixes"
        labels: pre-commit, auto-fix
        base: ${{ github.ref_name }}

    - name: Fail on unfixable pre-commit issues
      if: ${{ env.exit_code != '' && env.exit_code != '0' && env.exit_code != '1' }}
      run: |
        echo "Pre-commit failed with exit code ${{ env.exit_code }}"
        exit ${{ env.exit_code }}
