name: Test Report Generation

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI }}

    steps:
      - uses: actions/checkout@v3

      - name: setup OPEN_AI_TOKEN
        run: |
          sed -i "s/OPEN_AI_TOKEN=/OPEN_AI_TOKEN=${{ env.OPENAI_API_KEY }}/" ./deploiement-dev/.env
          cat ./deploiement-dev/.env

      - name: Set up Docker Compose
        run: |
          cd ./deploiement-dev
          docker compose up -d --build

      - name: Run Tests and Generate Report
        id: run_tests
        continue-on-error: true
        run: |
          mkdir -p auto_qcm/reports
          docker compose -f deploiement-dev/docker-compose.yml exec -T auto_qcm_python python manage.py behave --noinput -f behave_html_formatter:HTMLFormatter -o reports/rapport_tests.html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: auto_qcm/reports/rapport_tests.html
          retention-days: 30

      - name: Check Test Status
        if: steps.run_tests.outcome == 'failure'
        run: exit 1
