services:
  auto_qcm_python:
    container_name: auto_qcm_container
    build:
      context: ../
      dockerfile: Dockerfile
      target: ${env}
    depends_on:
      - auto_qcm_database
    env_file:
      - .env
    volumes:
      - ../auto_qcm:/app
    ports:
      - "8000:8000"

  auto_qcm_database:
    container_name: auto_qcm_db
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data